ifeq ($(BOARD_WLAN_DEVICE), bcmdhd)

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(TARGET_BOARD_PLATFORM),baytrail)
LOCAL_C_INCLUDES = \
	$(TARGET_OUT_HEADERS)/libtxei
else ifeq ($(TARGET_BOARD_PLATFORM),clovertrail)
LOCAL_C_INCLUDES = \
	$(TARGET_OUT_HEADERS)/chaabi
else
LOCAL_C_INCLUDES = \
	$(TARGET_OUT_HEADERS)/libdx_cc7
endif

LOCAL_SRC_FILES:= \
	wlan_provisioning.c

LOCAL_CFLAGS:=

ifeq ($(TARGET_BOARD_PLATFORM),baytrail)
LOCAL_CFLAGS += -DBUILD_WITH_CHAABI_SUPPORT
LOCAL_STATIC_LIBRARIES := \
	CC6_TXEI_UMIP_ACCESS CC6_ALL_BASIC_LIB
else ifeq ($(TARGET_BOARD_PLATFORM),clovertrail)
LOCAL_CFLAGS += -DBUILD_WITH_CHAABI_SUPPORT
LOCAL_STATIC_LIBRARIES := \
	CC6_UMIP_ACCESS CC6_ALL_BASIC_LIB
else
LOCAL_CFLAGS:= -DBUILD_WITH_TOKEN_SUPPORT
LOCAL_STATIC_LIBRARIES := \
	libdx_cc7_static
endif

ifeq ($(TARGET_BUILD_VARIANT),eng)
LOCAL_CFLAGS += -DWLAN_PROV_DEBUG_LOG_ENABLED
endif


LOCAL_SHARED_LIBRARIES := \
	libc libcutils libhardware_legacy libcrypto

LOCAL_MODULE:= wlan_prov.bcm
LOCAL_MODULE_STEM := wlan_prov
LOCAL_MODULE_TAGS := optional

include $(BUILD_EXECUTABLE)

endif
